2020-09-13 17:08:30,976 ERROR Exception on /attendance/group_select [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 156, in group_select
    groups = Student.query(group).all()
NameError: name 'group' is not defined
2020-09-13 17:09:01,320 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:09:04,303 ERROR Exception on /attendance/group_select [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 156, in group_select
    groups = Student.query.filter_by(group).all()
NameError: name 'group' is not defined
2020-09-13 17:10:08,461 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:11:09,600 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:12:11,700 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:13:39,549 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:13:44,183 ERROR Exception on /attendance/group_select [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a BaseQuery.
2020-09-13 17:20:20,299 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:30:12,352 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:30:27,166 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:31:59,057 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:32:15,909 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:35:55,410 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:37:47,020 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:37:49,256 ERROR Exception on /attendance/group_select [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 161, in group_select
    form.LogAttendanceGroupSelectForm.choises = groups
AttributeError: 'LogAttendanceGroupSelectForm' object has no attribute 'LogAttendanceGroupSelectForm'
2020-09-13 17:38:23,417 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:39:20,529 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:40:33,308 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:41:38,352 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:45:46,280 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:52:36,178 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:53:09,009 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:53:19,082 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:54:07,754 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:54:10,987 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:56:38,936 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:56:42,041 INFO Janus sartup [in %(lineno)d]
2020-09-13 17:56:55,036 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:02:45,937 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:02:48,069 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:03:53,973 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:03:56,360 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:04:00,974 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:04:21,475 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:04:46,463 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:05:12,575 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:05:17,214 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:05:23,325 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:06:11,923 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:06:15,625 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:07:25,265 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:07:38,373 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:07:43,618 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:08:58,044 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:09:00,533 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:09:09,356 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:09:44,206 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:10:03,236 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:10:11,020 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:11:08,714 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:38:03,403 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:38:29,511 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:39:38,448 INFO Janus sartup [in %(lineno)d]
2020-09-13 18:39:42,668 ERROR Exception on /add_groups [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 143, in add_groups
    form = GroupMarkingForm()
NameError: name 'GroupMarkingForm' is not defined
2020-09-13 18:40:05,729 INFO Janus sartup [in %(lineno)d]
