2020-09-09 16:39:06,618 INFO Janus sartup [in %(lineno)d]
2020-09-09 16:39:10,544 ERROR Exception on / [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 28, in index
    with open("/static/version.txt", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/static/version.txt'
2020-09-09 16:40:54,614 INFO Janus sartup [in %(lineno)d]
2020-09-09 16:40:57,259 ERROR Exception on / [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 28, in index
    with open('../static/version.txt', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../static/version.txt'
2020-09-09 16:41:58,577 INFO Janus sartup [in %(lineno)d]
2020-09-09 16:42:00,962 ERROR Exception on / [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 28, in index
    with open('../static/version_history.txt', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../static/version_history.txt'
2020-09-09 16:42:26,128 INFO Janus sartup [in %(lineno)d]
2020-09-09 16:42:28,579 ERROR Exception on / [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 28, in index
    with open('static/version_history.txt', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'static/version_history.txt'
2020-09-09 16:43:08,430 INFO Janus sartup [in %(lineno)d]
2020-09-09 16:43:10,920 ERROR Exception on / [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 28, in index
    with open('/static/Admin_manual.pdf', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/static/Admin_manual.pdf'
2020-09-09 16:45:12,714 INFO Janus sartup [in %(lineno)d]
2020-09-09 16:45:15,343 ERROR Exception on / [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 28, in index
    with open('/static/version_history.txt', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/static/version_history.txt'
2020-09-09 16:48:38,052 INFO Janus sartup [in %(lineno)d]
2020-09-09 16:49:13,568 INFO Janus sartup [in %(lineno)d]
2020-09-09 16:49:16,596 ERROR Exception on / [GET] [in %(lineno)d]
Traceback (most recent call last):
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kukri/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kukri/.local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kukri/Janus/app/routes.py", line 28, in index
    with open('/static/version_history.txt') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/static/version_history.txt'
2020-09-09 16:50:01,231 INFO Janus sartup [in %(lineno)d]
